exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/yirkajk/yirkajk.github.io"
